# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment_list.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63omment_list.proto\"\x1e\n\x0e\x43ommentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"?\n\rCommentResult\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x11\n\tsentiment\x18\x03 \x03(\x02\"4\n\x13\x43ommentsListRequest\x12\x1d\n\x04list\x18\x01 \x03(\x0b\x32\x0f.CommentRequest\"2\n\x12\x43ommentsListResult\x12\x1c\n\x04list\x18\x01 \x03(\x0b\x32\x0e.CommentResult\"\x07\n\x05\x45mpty2J\n\x12\x43ommentsPrediction\x12\x34\n\x07predict\x12\x14.CommentsListRequest\x1a\x13.CommentsListResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_list_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMENTREQUEST']._serialized_start=22
  _globals['_COMMENTREQUEST']._serialized_end=52
  _globals['_COMMENTRESULT']._serialized_start=54
  _globals['_COMMENTRESULT']._serialized_end=117
  _globals['_COMMENTSLISTREQUEST']._serialized_start=119
  _globals['_COMMENTSLISTREQUEST']._serialized_end=171
  _globals['_COMMENTSLISTRESULT']._serialized_start=173
  _globals['_COMMENTSLISTRESULT']._serialized_end=223
  _globals['_EMPTY']._serialized_start=225
  _globals['_EMPTY']._serialized_end=232
  _globals['_COMMENTSPREDICTION']._serialized_start=234
  _globals['_COMMENTSPREDICTION']._serialized_end=308
# @@protoc_insertion_point(module_scope)
